#!/bin/bash

export BENCHTOOL=$(dirname "$(realpath $BASH_SOURCE)")
ml use "$BENCHTOOL/build/modulefiles"
ml builder
alias cdb='cd $BENCHTOOL'

if [ $(stat -c %U $BENCHTOOL/hw_utils/lshw ) != 'root' ]; then
    echo "WARNING: please run 'sudo hw_utils/change_permissions.sh' if you plan to collect hardware stats."
fi
