#!/bin/env bash

if [[ -z $1 ]]; then 
    printf "Missing collection output path. Aborting\n"
    exit 1
fi

src_path=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
dest_path=$1

mkdir -p ${dest_path}

label=( "cpuid.all.raw" 
        "cpuid.core0" 
        "lshw" 
        "TACC_HWP_set" 
        "lspci" 
        "rdmsr_all"
        "rpm" 
        "ml"
        "lscpu"
        ) 

cmd=(   "cpuid -r"
        "cpuid -1"
        "lshw"
        "TACC_HWP_set -v -s"
        "lspci -xxx"
        "rdmsr_all"
        "rpm -qa"
        "ml"
        "lscpu"
        )

for ((i=0;i<${#label[@]};++i)); do
    echo "Running ${label[i]}"

    script=${src_path}/${cmd[i]}
    if [[ ! -f ${script} ]]; then
        script=${cmd[i]}
    fi

    ${script} &> ${dest_path}/${label[i]}
done
echo "Done."
exit 0
