#!/usr/bin/env bash
# Script to swap between development and production installations of BenchPRO
# Matthew Cawood
# April 2022
# v2.0 - generalized for different systems

if [ -z $BPS_HOME ]; then
    echo "No BenchPRO module loaded."
    exit 1
fi

BP_ROOT=$(dirname $BPS_HOME)

# DEV currently loaded
if [[ $BP_DEV -eq 1 ]]; then
    ml unuse    $BP_ROOT/benchpro-dev/modulefiles
    ml use      $BP_ROOT/benchpro/modulefiles
# PROD currently loaded
else
    ml unuse    $BP_ROOT/benchpro/modulefiles
    ml use      $BP_ROOT/benchpro-dev/modulefiles
fi

ml benchpro

build="[PROD]"
[[ $BP_DEV -eq 1 ]] && build="[DEV]"

version=$BP_SITE_VERSION
[[ -z "$BP_SITE_VERSION" ]] && version=$BPS_VERSION_STR

echo "Switched to ${version} ${build} in $(which benchpro)"

return 0
